name: Test action-workflow
env:
  ACCESS_KEY: z1e5KuyQoXYFVZTX1Jair7yHBU7k5MwomD2
  ACCESS_SECRET: zgsGfbgYkmCYYpfFhFY5QY2rsXTPWw3DDjrrZ9aQRpZ9WgkczYiDbdP6ELay1GnDSDkXtQ6vAiiWLNZJfyTZhbc5
  DEVELOPER_SK: 0x6b55315d865ee61f0d2ff7e93df057a09f6985f77c2a6376ca05f64aa2bf72129f2f1b8c6b13836c36a7272d33a77d475e63770243610a3c26aabd07501ad283
  REGISTRY: https://8080-fuchsia-cicada-r1hvnx90.ws-us17.gitpod.io/admin/blocklet-registry-service/publicUrl/
  ABTNODE: https://8080-fuchsia-cicada-r1hvnx90.ws-us17.gitpod.io/admin/api

on:
  push:
    branches:
      - main
jobs:
  packages:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set yarn cache
        uses: c-hive/gha-yarn-cache@v2

      - name: Install dependencies
        run: |
          yarn global add @abtnode/cli
          lerna bootstrap

      - name: Publish Blocklet dapp
        uses: blocklet/action-workflow@v1
        with:
          skip-abtnode: true
          skip-upload: false
          skip-deploy: false
          skip-release: true
          working-directory: packages/dapp
          bundle-command: yarn bundle
          registry-endpoint: ${{env.REGISTRY}}
          developer-sk: ${{env.DEVELOPER_SK}}
          abtnode-endpoint: ${{env.ABTNODE}}
          access-key: ${{env.ACCESS_KEY}}
          access-secret: ${{env.ACCESS_SECRET}}

      - name: Publish Blocklet static
        uses: blocklet/action-workflow@v1
        with:
          skip-abtnode: true
          skip-upload: false
          skip-deploy: false
          skip-release: true
          working-directory: packages/static
          bundle-command: yarn bundle
          registry-endpoint: ${{env.REGISTRY}}
          developer-sk: ${{env.DEVELOPER_SK}}
          abtnode-endpoint: ${{env.ABTNODE}}
          access-key: ${{env.ACCESS_KEY}}
          access-secret: ${{env.ACCESS_SECRET}}
