name: Test action-workflow

on:
  push:
    branches:
      - main
jobs:
  packages:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
          token: ${{ secrets.GIT_HUB_TOKEN }}

      - name: Set yarn cache
        uses: c-hive/gha-yarn-cache@v2

      - name: Install dependencies
        run: lerna bootstrap

      - name: Publish Blocklet dapp
        uses: blocklet/action-workflow@v1
        with:
          skip-abtnode: true
          skip-release: true
          working-directory: packages/dapp
          bundle-command: yarn bundle

      - name: Publish Blocklet static
        uses: blocklet/action-workflow@v1
        with:
          skip-abtnode: true
          skip-release: true
          working-directory: packages/static
          bundle-command: yarn bundle
